#ident "@(#)Makefile	1.3 06/09/15 "
###########################################################################
SRCROOT=	..
RULESDIR=	RULES
include		$(SRCROOT)/$(RULESDIR)/rules.top
###########################################################################

MK_FILES= libedc.mk libedc_p.mk libedc_dec.mk libedc_dec_p.mk \
		$(NO_SHL)shledc.mk $(NO_SHL)shledc_dec.mk

###########################################################################
include		$(SRCROOT)/$(RULESDIR)/rules.mks
###########################################################################
