#!/bin/bash

# Dreamcast CDI Burner build script

set -e
version=v1.0.8
arch=$(uname -m)

cd "$(dirname "$0")"
rm -rf build-tmp dcdib-$version-$arch dcdib-$version-$arch.zip

# Just clean built binaries/releases from source and exit now if given the argument 'clean'
if [ "$1" == "clean" ]; then
    exit 0
fi

mkdir -p build-tmp dcdib-$version-$arch/bin dcdib-$version-$arch/licenses
cp -r cdirip build-tmp
cd build-tmp/cdirip
make -f Makefile.linux
../../pled/pled ./cdirip ../../dcdib-$version-$arch/bin
cd ../../

cp -rv cdrtools build-tmp
cd build-tmp/cdrtools
make GMAKE_NOWARN=true

# Use * here because the begining name of the parent folder differs by architecture/OS/compiler
../../pled/pled ./cdrecord/OBJ/*cc/cdrecord ../../dcdib-$version-$arch/bin
cd ../../
rm -rf build-tmp

# Copy licenses to release
cp -r unlicense.txt dcdib-$version-$arch/licenses/dcdib.txt
cp -r pled/unlicense.txt dcdib-$version-$arch/licenses/pled.txt
cp -r cdirip/LICENSE dcdib-$version-$arch/licenses/cdirip-gpl2.txt
cp -r cdrtools/GPL-2.0.txt dcdib-$version-$arch/licenses/cdrecord-gpl2.txt
cp -r cdrtools/CDDL.Schily.txt dcdib-$version-$arch/licenses/cdrecord-cddl.txt

# Copy documentation to release
cp -r dcdib readme.md images dcdib-$version-$arch/
chmod -R 777 dcdib-$version-$arch
zip -r dcdib-$version-$arch.zip dcdib-$version-$arch
