#!/bin/bash

# When this script exits, automatically delete the temp directory.
cleanup() { if [[ -e "$tmp" ]]; then  rm -r "$tmp";   fi; }
trap cleanup EXIT

# Print out any uncaught errors.
err() {	echo "Uncaught error in $0:$BASH_LINENO" >&2; }
trap err ERR

# If any command unexpectedly exits with an error, quit the whole script. 
set -e 

# Put temp directory in /tmp (or whatever the OS prefers)
tmp=$(mktemp -d --tmpdir cdib.XXX)
os=$(uname)

unmount_cd () {
    if [ "$os" = "Darwin" ]; then
	launchctl unload /System/Library/LaunchDaemons/com.apple.diskarbitrationd.plist > /dev/null 2>&1
	disktool -u disk1 0 > /dev/null 2>&1
    else
	( pumount cdrom ||	     		# Easiest
	      umount /media/cdrom || 		# Most common
	      umount /mnt/cdrom	     		# For old systems
	)> /dev/null 2>&1  || true
    fi
}

if [ "$#" -ne 1 ]; then
    cat >&2 <<-EOF
	Usage:
	        cdib <file.cdi>

	where <file.cdi> is the .cdi file you'd like to burn to disc.
	EOF
    exit 1
fi

if [ ! -f "$1" ]; then
    echo "Error: Can not open CDI file: "$1""
    exit 1
fi

PATH=".:/Applications/DCDIB.app/bin:/usr/local/dreamcast-cdi-burner/bin:$PATH"
if ! type cdrecord >/dev/null 2>&1; then
    echo "Error: cdrecord is not installed" >&2
    exit 1
fi
if ! type cdirip >/dev/null 2>&1; then
    echo "Error: cdirip is not installed" >&2
    exit 1
fi

if [[ "$os" = "Darwin"  ]]; then
    device="dev=IODVDServices"
else
    device="dev=/dev/sr0"
fi

if [[ "$os" = "Darwin" && $EUID -ne 0 ]]; then 
    echo "$USER does not have the required privilages to run $0. Execute sudo $0 to continue." 
    exit 1 
fi

unmount_cd

echo "Extracting cdi..."
cdirip "$1" $tmp 
cd $tmp 


echo "Burning..."
if [ -f "taudio01.wav" ]; then
    echo "Detected CDI Type: WAV Track 1"
    unmount_cd
    cdrecord -speed=8 -v $device -dao -multi *.wav

    unmount_cd
    cdrecord -eject -overburn -speed=8 -v $device -tao -xa *.iso
    
    unmount_cd

elif [ -f "tdata01.iso" ]; then
    echo "Detected CDI Type: ISO Track 1"
    unmount_cd
    cdrecord -speed=8 -v $device -tao -multi -xa tdata01.iso

    unmount_cd
    cdrecord -eject -overburn -speed=8 -v $device -tao -multi -xa tdata02.iso
    
    unmount_cd
else
    echo "Failed To Find Burn Files, Nothing Burned!"
    exit 1
fi

unmount_cd

if [ "$os" = "Darwin" ]; then
    if [ -f "/usr/bin/drutil" ]; then
	echo "Ejecting CD-ROM, please wait..."
	drutil eject cd
    fi
    launchctl load /System/Library/LaunchDaemons/com.apple.diskarbitrationd.plist > /dev/null 2>&1
    if [ -f "/usr/bin/afplay" ]; then
	if [ -f "/System/Library/Sounds/Glass.aiff" ]; then
	    afplay /System/Library/Sounds/Glass.aiff
	fi
    fi
else
    echo "Ejecting CD-ROM, please wait..."
    eject || true
fi

echo "Complete!"
