#ident "@(#)Makefile.doc	1.1 07/06/13 "
###########################################################################
# Sample makefile for sub-makes in one directory
###########################################################################
SRCROOT=	..
RULESDIR=	RULES
include		$(SRCROOT)/$(RULESDIR)/rules.top
###########################################################################

MK_FILES=	readme.mk Rata-dma.mk Ratapi-dma.mk Ratapi.mk Raudio.mk \
		Rcdplus.mk Rcdrw.mk Rcdtext.mk Rclone.mk Rcopy.mk \
		Rdisktattoo.mk Rmulti.mk \
		Rparallel.mk Rraw.mk Rrscsi.mk Rsony.mk Rsun-lofi.mk \
		Rverify.mk Rvolmgt.mk Rworm.mk

#XMK_FILE=	Makefile.man

###########################################################################
include		$(SRCROOT)/$(RULESDIR)/rules.mks
###########################################################################
