#ident "@(#)Makefile.doc	1.1 07/06/14 "
###########################################################################
# Sample makefile for sub-makes in one directory
###########################################################################
SRCROOT=	..
RULESDIR=	RULES
include		$(SRCROOT)/$(RULESDIR)/rules.top
###########################################################################

MK_FILES=	Rcompresion.mk Reltorito.mk Rgraft_dirs.mk Rhfs_boot.mk \
		Rhfs_magic.mk Rhide.mk Rjoliet.mk Rmacosx.mk Rmkhybrid.mk \
		Rprep_boot.mk readme.mk Rrootinfo.mk Rsession.mk Rsort.mk \
		Rsparcboot.mk Rsunx86boot.mk

#XMK_FILE=	Makefile.man

###########################################################################
include		$(SRCROOT)/$(RULESDIR)/rules.mks
###########################################################################
