#ident "@(#)Makefile	1.1 07/05/19 "
###########################################################################
# Sample makefile for installing non-localized auxiliary files
###########################################################################
SRCROOT=	../..
RULESDIR=	RULES
include		$(SRCROOT)/$(RULESDIR)/rules.top
###########################################################################

INSDIR=		lib/siconv
TARGET=		iso8859-1
XMK_FILE=	\
		cp10000.mk cp10006.mk cp10007.mk cp10029.mk cp10079.mk \
		cp10081.mk cp1250.mk cp1251.mk cp1252.mk cp1253.mk cp1254.mk \
		cp1255.mk cp1256.mk cp1257.mk cp1258.mk cp437.mk cp737.mk \
		cp775.mk cp850.mk cp852.mk cp855.mk cp857.mk cp860.mk cp861.mk \
		cp862.mk cp863.mk cp864.mk cp865.mk cp866.mk cp869.mk cp874.mk \
		iso8859-1.mk iso8859-10.mk iso8859-11.mk iso8859-13.mk \
		iso8859-14.mk iso8859-15.mk iso8859-16.mk iso8859-2.mk \
		iso8859-3.mk iso8859-4.mk iso8859-5.mk iso8859-6.mk \
		iso8859-7.mk iso8859-8.mk iso8859-9.mk koi8-r.mk koi8-u.mk

###########################################################################
include		$(SRCROOT)/$(RULESDIR)/rules.aux
###########################################################################
