#!/bin/bash
set -e
echo "Build Select by Alex Free 
v1.0.1, 2020"

if [ ! -d "/Developer" ]; then
echo "Xcode must be installed to /Developer to use "$0""
exit 1
fi

if [ "$1" = "--help" ]; then
echo "
Usage: 
bselect --help	Display this text.
bselect --reset Reset to the default xcode compiler setup.
bselect <compiler_version> <sdk_version> <arch> <macosx_deployment_target> <additional_flags>

The first argument is the compiler version. Valid options are 3.3, 4.0, and 4.2.

The second argument is the SDK version. Valid options are 10.3.9, 10.4u, and 10.5.

The third argument is the arch to compile for. Valid options are ppc, ppc750, ppc7400, ppc7450, and ppc970. If you compile for a newer arch then what your Mac is itself, you will not be able to execute what you compile on that Mac.

The fourth argument is the MACOSX_DEPLOYMENT_TARGET value. This may be the same as your SDK or lower. Valid options are 10.3, 10.4, and 10.5.

The fifth argument of additional flags is the only argument that is optional. If you specify additional flags that contain spaces, you must double quote them.

Example: Compile with the GCC 4.2 compiler using the MAC OS X 10.4u SDK for the generic ppc arch at the Mac OS X 10.3 panther API value. Targets Mac OS X 10.3.9 ppc.
"$0" 4.2 10.4u ppc 10.3 "'"-I/usr/local/my_custom_include_dir -L/usr/local/my_custom_lib_dir"'""
exit 0
fi

 if [ "$EUID" -ne 0 ]; then
 echo "$USER does not have the required privilages to execute "$0", execute sudo "$0""
 exit 1
 fi
 
 if [ "$1" = "--reset" ]; then
rm -rf /usr/bin/gcc /usr/bin/cc /usr/bin/c++ /usr/bin/g++
ln -s /usr/bin/gcc-4.0 /usr/bin/cc
ln -s /usr/bin/gcc-4.0 /usr/bin/gcc
ln -s /usr/bin/g++-4.0 /usr/bin/g++
ln -s /usr/bin/c++-4.0 /usr/bin/c++
echo "Xcode compiler has been reset to defaults.
"
gcc --version
g++ --version
exit 0
fi

if [ ! -e "/usr/bin/gcc-4.2" ] && [ "$1" = 4.2 ]; then
echo "Error: GCC 4.2 is not installed, this is expected when using older Xcode versions and or an OS older then Leopard. You may not select this compiler."
exit 1
fi

if [ ! -e "/usr/bin/gcc-3.3" ] && [ "$1" = 3.3 ]; then
echo "Error: GCC 3.3 is not installed, you may have not selected it when installing Xcode. You may not select this compiler."
exit 1
fi
if [ -z "$1" ]; then
	echo "First argument must be 3.3, 4.0, or 4.2"
	exit 1
else
	if [ "$1" = 3.3 ] || [ "$1" = 4.0 ] || [ "$1" = 4.2 ]; then
	echo "Compiler: GCC "$1""
	else
	echo 
	echo ""$1" is not 3.3, 4.0, or 4.2."
	exit 1
	fi
fi

if [ -z "$2" ]; then
	echo "Second argument must be 10.3.9, 10.4u, or 10.5"
	exit 1
else
	if [ "$2" = 10.3.9 ] || [ "$2" = 10.4u ] || [ "$2" = 10.5 ]; then
	echo "SDK: "$2""
	else
	echo 
	echo "SDK "$2" is not 10.3.9, 10.4u, or 10.5"
	exit 1
	fi
fi

if [ -z "$3" ]; then
	echo "Third argument must be ppc, ppc750, ppc7400, ppc7450, or ppc970"
	exit 1
else
	if [ "$3" = ppc750 ] || [ "$3" = ppc7400 ] || [ "$3" = ppc7450 ] || [ "$3" = ppc970 ] || [ "$3" = ppc ];then
	echo "Arch: "$3""
	else
	echo 
	echo "Arch "$3" is not ppc, ppc750, ppc7400, ppc7450, or ppc970"
	exit 1
	fi
fi

if [ -z "$4" ]; then
	echo "Forth argument must be 10.3, 10.4, or 10.5"
	exit 1
else
	if [ "$4" = 10.3 ] || [ "$4" = 10.4 ] || [ "$4" = 10.5 ];then
	echo "MACOSX_DEPLOYMENT_TARGET: "$4""
	else
	echo 
	echo "MACOSX_DEPLOYMENT_TARGET "$4" is not 10.3, 10.4, or 10.5"
	exit 1
	fi
fi

rm -rf /usr/bin/gcc /usr/bin/cc /usr/bin/c++ /usr/bin/g++
if [ -z "$5" ]; then
echo "#!/bin/bash
/usr/bin/gcc-"$1" -arch "$3" -isysroot/Developer/SDKs/MacOSX"$2".sdk -mmacosx-version-min="$4" "'"$@"'"" > /usr/bin/cc
echo "#!/bin/bash
/usr/bin/gcc-"$1" -arch "$3" -isysroot/Developer/SDKs/MacOSX"$2".sdk -mmacosx-version-min="$4" "'"$@"'"" > /usr/bin/gcc
echo "#!/bin/bash
/usr/bin/c++-"$1" -arch "$3" -isysroot/Developer/SDKs/MacOSX"$2".sdk -mmacosx-version-min="$4" "'"$@"'"" > /usr/bin/c++
echo "#!/bin/bash
/usr/bin/g++-"$1" -arch "$3" -isysroot/Developer/SDKs/MacOSX"$2".sdk -mmacosx-version-min="$4" "'"$@"'"" > /usr/bin/g++
else
echo "Additional flags: "$5""
echo "#!/bin/bash
/usr/bin/gcc-"$1" -arch "$3" -isysroot/Developer/SDKs/MacOSX"$2".sdk -mmacosx-version-min="$4" "$5" "'"$@"'"" > /usr/bin/cc
echo "#!/bin/bash
/usr/bin/gcc-"$1" -arch "$3" -isysroot/Developer/SDKs/MacOSX"$2".sdk -mmacosx-version-min="$4" "$5" "'"$@"'"" > /usr/bin/gcc
echo "#!/bin/bash
/usr/bin/c++-"$1" -arch "$3" -isysroot/Developer/SDKs/MacOSX"$2".sdk -mmacosx-version-min="$4" "$5" "'"$@"'"" > /usr/bin/c++
echo "#!/bin/bash
/usr/bin/g++-"$1" -arch "$3" -isysroot/Developer/SDKs/MacOSX"$2".sdk -mmacosx-version-min="$4" "$5"  "'"$@"'"" > /usr/bin/g++
fi

chmod -R 775 /usr/bin/cc /usr/bin/gcc /usr/bin/c++ /usr/bin/g++
