. \"  Manual Seite fuer filesize
. \" @(#)filesize.3	1.1
. \"
.if t .ds a \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'a
.if t .ds o \v'-0.55m'\h'0.00n'\z.\h'0.45n'\z.\v'0.55m'\h'-0.45n'o
.if t .ds u \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'u
.if t .ds A \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'A
.if t .ds O \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'O
.if t .ds U \v'-0.77m'\h'0.30n'\z.\h'0.45n'\z.\v'0.77m'\h'-.75n'U
.if t .ds s \(*b
.if t .ds S SS
.if n .ds a ae
.if n .ds o oe
.if n .ds u ue
.if n .ds s sz
.TH FILESIZE 3 "15. Juli 1988" "J\*org Schilling" "Schily\'s LIBRARY FUNCTIONS"
.SH NAME
filesize() \- returns size of file
.SH SYNOPSIS
.nf
.B
long filesize(f)
.B	FILE *f;
.fi
.SH DESCRIPTION
filesize() returns the file size in bytes.
.SH RETURNS
.TP
.B >= 0
filesize.
.TP
.B < 0
an error code.
.SH NOTES
If the file was written in the current process and was buffered,
do a fflush() before using filesize()
..PP
NOTE: The call does not work on terminals or other devices.
