. \"  Manual Seite fuer fileseek
. \" @(#)fileseek.3	1.1
. \"
.if t .ds a \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'a
.if t .ds o \v'-0.55m'\h'0.00n'\z.\h'0.45n'\z.\v'0.55m'\h'-0.45n'o
.if t .ds u \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'u
.if t .ds A \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'A
.if t .ds O \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'O
.if t .ds U \v'-0.77m'\h'0.30n'\z.\h'0.45n'\z.\v'0.77m'\h'-.75n'U
.if t .ds s \(*b
.if t .ds S SS
.if n .ds a ae
.if n .ds o oe
.if n .ds u ue
.if n .ds s sz
.TH FILESEEK 3 "15. Juli 1988" "J\*org Schilling" "Schily\'s LIBRARY FUNCTIONS"
.SH NAME
fileseek() \- sets file position
.SH SYNOPSIS
.nf
.B
fileseek(f,offset)
.B	FILE *f;
.B	long offset;
.fi
.SH DESCRIPTION
fileseek() sets the logical position in the file f to offset.
The next read or write operation begins with the byte at the new
offset.
.SH RETURNS
none
.SH NOTES
File positions begin with 0 for the first byte. When writing,
it is legal to seek beyond the end of file.
