. \"  Manual Seite fuer fprintf
. \" @(#)fprintf.3	1.1
. \"
.if t .ds a \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'a
.if t .ds o \v'-0.55m'\h'0.00n'\z.\h'0.45n'\z.\v'0.55m'\h'-0.45n'o
.if t .ds u \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'u
.if t .ds A \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'A
.if t .ds O \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'O
.if t .ds U \v'-0.77m'\h'0.30n'\z.\h'0.45n'\z.\v'0.77m'\h'-.75n'U
.if t .ds s \(*b
.if t .ds S SS
.if n .ds a ae
.if n .ds o oe
.if n .ds u ue
.if n .ds s sz
.TH FPRINTF 3 "15. Juli 1988" "J\*org Schilling" "Schily\'s LIBRARY FUNCTIONS"
.SH NAME
fprintf() \- formats and prints to a file
.SH SYNOPSIS
.nf
.B
fprintf(file, format, arg1, \|.\|.\|., argn)
.B	FILE *file;
.B	char *format;
.fi
.SH DESCRIPTION
fprintf formats its arguments using the format() routine, and
writes the result on the given file.
.PP
See format() for information about the available formatting
options.
.SH RETURNS
none
.SH "SEE ALSO"
format(3), printf(3)
.SH NOTES
none
