. \"  Manual Seite fuer movebytes
. \" @(#)movebytes.3	1.3 17/02/08 Copyright 1988-2017 J. Schilling
. \"
.if t .ds a \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'a
.if t .ds o \v'-0.55m'\h'0.00n'\z.\h'0.45n'\z.\v'0.55m'\h'-0.45n'o
.if t .ds u \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'u
.if t .ds A \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'A
.if t .ds O \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'O
.if t .ds U \v'-0.77m'\h'0.30n'\z.\h'0.45n'\z.\v'0.77m'\h'-.75n'U
.if t .ds s \(*b
.if t .ds S SS
.if n .ds a ae
.if n .ds o oe
.if n .ds u ue
.if n .ds s sz
.TH MOVEBYTES 3 "2017/02/08" "J\*org Schilling" "Schily\'s LIBRARY FUNCTIONS"
.SH NAME
movebytes() \- moves data
.SH SYNOPSIS
.nf
.B
char *movebytes(from, to, size)
.B		const void	*from;
.B		void			*to;
.B		ssize_t		size;
.fi
.SH DESCRIPTION
.B movebytes()
copies
.I size
bytes from
.I from
to
.IR to .
.SH RETURN VALUE
A pointer just after the last transferred byte in the
.I to
string.
.SH ERRORS
.LP
No errors are defined
.SH EXAMPLES
.SH "SEE ALSO"
.LP
.BR cmpbytes (3),
.BR cmpmbytes (3),
.BR cmpnullbytes (3),
.BR fillbytes (3),
.BR findbytes (3),
.BR movecbytes (3),
.BR swapbytes (3),
.BR zerobytes (3)
.SH NOTES
This routine correctly handles overlapping buffers.
