. \"  Manual Seite fuer spawnl
. \" @(#)spawnl.3	1.1
. \"
.if t .ds a \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'a
.if t .ds o \v'-0.55m'\h'0.00n'\z.\h'0.45n'\z.\v'0.55m'\h'-0.45n'o
.if t .ds u \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'u
.if t .ds A \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'A
.if t .ds O \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'O
.if t .ds U \v'-0.77m'\h'0.30n'\z.\h'0.45n'\z.\v'0.77m'\h'-.75n'U
.if t .ds s \(*b
.if t .ds S SS
.if n .ds a ae
.if n .ds o oe
.if n .ds u ue
.if n .ds s sz
.TH SPAWNL 3 "15. Juli 1988" "J\*org Schilling" "Schily\'s LIBRARY FUNCTIONS"
.SH NAME
spawnl() \- calls a command with specified arguments
.SH SYNOPSIS
.nf
.B
int spawnl(Sin,Sout,Serr,Command_Name,arg1\|.\|.\|.argn,NULL)
.B	FILE *Sin, *Sout, *Serr;
.B	char *Command_Name, *arg1\|.\|.\|.*argn;
.SH DESCRIPTION
spawnl() causes the named command to be called in a subsidiary
process with the given arguments. The last argument to spawnl()
must be NULL to indicate the end of the list. The streams Sin,
Sout and Serr become stdin, stout, and stderr for the command.
The Command_Name may be an absolute or a relative pathname. To
locate the command, the working directory is searched first,
then /bin. This is a property of fexecv(), which spawnl()
calls.
.PP
When the command finishes, spawnl() returns to the caller.
.SH RETURNS
Returns 0 when successful. Otherwise, returns a non-zero value
which could be:
.PP
an error code from fork() or fexecl().
the argument to exit() in the Command_name.
.TP
.B 1,
if stopped by a control C (^C).
.TP
.B 2,
if killed by another process.
.TP
.B 4,
if suspended by any fault, raise, control Y ^Y or by
another process. (In this case, spawnl() kills the
suspended process.)
.SH NOTES
spawnl() just calls spawnv() with the address and length of the
argument list.
