. \"  Manual Seite fuer sprintf
. \" @(#)sprintf.3	1.1
. \"
.if t .ds a \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'a
.if t .ds o \v'-0.55m'\h'0.00n'\z.\h'0.45n'\z.\v'0.55m'\h'-0.45n'o
.if t .ds u \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'u
.if t .ds A \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'A
.if t .ds O \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'O
.if t .ds U \v'-0.77m'\h'0.30n'\z.\h'0.45n'\z.\v'0.77m'\h'-.75n'U
.if t .ds s \(*b
.if t .ds S SS
.if n .ds a ae
.if n .ds o oe
.if n .ds u ue
.if n .ds s sz
.TH SPRINTF 3 "15. Juli 1988" "J\*org Schilling" "Schily\'s LIBRARY FUNCTIONS"
.SH NAME
sprintf() \- formats and places output in buffer
.SH SYNOPSIS
.nf
.B
sprintf(buf,form,arg1\|.\|.\|.argn)
.B	char *buf;
.B	char *form;
.fi
.SH DESCRIPTION
sprintf() is similar to fprintf() except the formatted output is
placed into buf.
.SH RETURNS
none
.SH "SEE ALSO"
format(3), printf(3)
.SH NOTES
A NULL ('\\0') is appended to the end of the formatted output.
There is no check for overflowing the buffer.
