. \"  Manual Seite fuer streql
. \" @(#)streql.3	1.1
. \"
.if t .ds a \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'a
.if t .ds o \v'-0.55m'\h'0.00n'\z.\h'0.45n'\z.\v'0.55m'\h'-0.45n'o
.if t .ds u \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'u
.if t .ds A \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'A
.if t .ds O \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'O
.if t .ds U \v'-0.77m'\h'0.30n'\z.\h'0.45n'\z.\v'0.77m'\h'-.75n'U
.if t .ds s \(*b
.if t .ds S SS
.if n .ds a ae
.if n .ds o oe
.if n .ds u ue
.if n .ds s sz
.TH STREQL 3 "15. Juli 1988" "J\*org Schilling" "Schily\'s LIBRARY FUNCTIONS"
.SH NAME
streql() \- compares two strings for equality
.SH SYNOPSIS
.nf
.B
BOOL streql(s1,s2) 
.B	char *s1, *s2;
.fi
.SH DESCRIPTION
streql() checks two strings for equality.
.SH RETURNS
Returns TRUE if the string s1 is the same length and has the
same characters as s2. Otherwise, returns FALSE.
.SH NOTES
When comparing two strings, the strings are not considered equal
if one has padding (extra spaces).
