#ident @(#)Makefile	1.22 13/10/27 
###########################################################################
# Sample makefile for installing non-localized auxiliary files
###########################################################################
SRCROOT=	../..
RULESDIR=	RULES
include		$(SRCROOT)/$(RULESDIR)/rules.top
###########################################################################

INSDIR=		include/schily
TARGET=		align.h

include Targets
XMK_FILE=	$(X_MK_LIST)

###########################################################################
include		$(SRCROOT)/$(RULESDIR)/rules.aux
###########################################################################

